### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by stevenabreu7**
Add note for M1

### CODE REVIEW

**Comment by fabhertz95** [comment]
Hi! Thank you very much :) 
We are trying a different solution which should be better: uploading the source `tar.gz` to PyPi directly. Could you uninstall the cloned package and try to install it from PyPi through `pip` and tell us if it works properly? Thank you :)

**Comment by stevenabreu7** [comment]
Nice, even better! It seems to be missing the C header file, running `pip install expelliarmus` fails with: 

```
Collecting expelliarmus
  Using cached expelliarmus-1.1.3.tar.gz (20 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in /Users/steve/.pyenv/versions/3.8.10/lib/python3.8/site-packages (from expelliarmus) (1.22.3)
Building wheels for collected packages: expelliarmus
  Building wheel for expelliarmus (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [24 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.macosx-12.2-arm64-cpython-38
      creating build/lib.macosx-12.2-arm64-cpython-38/expelliarmus
      copying expelliarmus/__init__.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus
      copying expelliarmus/utils.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus
      creating build/lib.macosx-12.2-arm64-cpython-38/expelliarmus/wizard
      copying expelliarmus/wizard/wizard_wrapper.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus/wizard
      copying expelliarmus/wizard/__init__.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus/wizard
      copying expelliarmus/wizard/wizard.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus/wizard
      copying expelliarmus/wizard/clib.py -> build/lib.macosx-12.2-arm64-cpython-38/expelliarmus/wizard
      running build_ext
      building 'expelliarmus' extension
      creating build/temp.macosx-12.2-arm64-cpython-38
      creating build/temp.macosx-12.2-arm64-cpython-38/expelliarmus
      creating build/temp.macosx-12.2-arm64-cpython-38/expelliarmus/src
      clang -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include -I/Users/steve/.pyenv/versions/3.8.10/include/python3.8 -c expelliarmus/src/wizard.c -o build/temp.macosx-12.2-arm64-cpython-38/expelliarmus/src/wizard.o
      expelliarmus/src/wizard.c:1:10: fatal error: 'wizard.h' file not found
      #include "wizard.h"
               ^~~~~~~~~~
      1 error generated.
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for expelliarmus
  Running setup.py clean for expelliarmus
Failed to build expelliarmus

× Encountered error while trying to install package.
╰─> expelliarmus

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by fabhertz95** [comment]
Could you try now?

**Comment by fabhertz95** [comment]
Nice :) I see that `expelliarmus` is being used in one of you projects and I am really happy about it :) May I ask why you are converting the data from EVT3 to NPY?

**Comment by stevenabreu7** [comment]
Yeah, I saw your post about the release on Twitter and wanted to check it out right away :) I'm using a prophesee camera and used their Python SDK for the conversion before but it's not compatible with the M1 so I always had to move data back and forth between two different machines - now I'm very happy that I can do it directly with expelliarmus (also quicker and simpler code & installation). Then I'm transforming the numpy data with tonic and feeding it into a SNN for a classification task. 

Thanks for your work! 🚀 And lmk if I can help in any way (e.g. happy to report M1 support whenever).

**Comment by fabhertz95** [comment]
AWESOME! This is exactly why we (@biphasic) started this project :) It makes me very happy that someone else is benefitting from it! If you can give some feedback on how much faster is to pre-save recordings to NPY format instead of reading directly EVT3 with expelliarmus, I would appreciate it :) Also because NumPy compresses much less, if you take a look at the benchmarks.

For dealing directly with cameras, you can take a look also at the [AEStream project](https://github.com/norse/aestream), that allows to load data from the camera directly to GPU in form of PyTorch tensors really fast (unless you need some preprocessing before; in that case, it is better to use expelliarmus and tonic transforms).

**Comment by fabhertz95** [comment]
Damn! I have to work harder to be faster than NumPy :) I don’t think that
it is feasible because the high compression comes at the expense of reduced
read speed but I’ll try :)

Thank you very much! If you have any features in mind or you would like to
write some dirty code, let me know eheheh

Il giorno mar 29 nov 2022 alle 17:17 Steven Abreu ***@***.***>
ha scritto:

**Comment by stevenabreu7** [comment]
Yeah I imagine it will be difficult to be faster than loading from a numpy array (but I also don't think it's necessary to be faster for expelliarmus to be useful). Yes would love to help! If you have anything in mind, please feel free to reach out :)

**Comment by stevenabreu7** [comment]
I ran a simple benchmark using the EVT2 file I have and with the code that I have (see issue #6), I get really good results! 

```
%timeit load_metavision()
6.14 s ± 24.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit load_expelliarmus()
1.76 s ± 903 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Looks like a 3x speedup! But to be fair, I don't know if my metavision code is the best (perhaps the `RawReader` is faster than the `EventsIterator`).

**Comment by fabhertz95** [comment]
Seems wonderful :) I think that for a fair comparison, you should use the `read_chunk()` method in `expelliarmus`, or the `read()` one but using the `RAWReader` in Metavision.

**Comment by stevenabreu7** [comment]
But the `RawReader` only has the `load_n_events` or `load_delta_t` methods, there is no method to read the whole file at once is there? Calling `load_n_events` with the number of events that the file has crashes for me, and iterating gives me:
```python
def load_raw_metavision():
    rr = RawReader("../data/raw/A1.raw")
    events = []
    while not rr.is_done():
        events.append(rr.load_n_events(10000))
    arr = np.concatenate(events)
```
```
%timeit load_raw_metavision()
6.57 s ± 29.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
Is there a more efficient way to read the whole file with metavision?

**Comment by fabhertz95** [comment]
Uhm from what I saw in the API, they provide an argument for the maximum number of events than you can read in an array. They probably do this to preallocate the resulting event and maybe you get a RAM crash. I don't know their API very well, unfortunately :( I am working on the bug you signalled so that you can use expelliarmus as soon as possible.

**Pull request closed without merging**
